config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path: '',
                      path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register',    password: 'secret', confirmation: 'verification', unlock: 'unblock' },
                      controllers: { registrations: 'registrations', invitations: 'invitations'}

  # resources :bookmarks
  # resources :collections

  # After authenticated, send user to this page
  authenticated :user do
    root 'collections#index', as: :authenticated_root
  end

  # unauthenticated :user do
  #   root 'devise/sessions#new', as: :unauthenticated_root
  # end

  # While I can't figure out how to force the user to be logged in
  root 'collections#index'


  # Inside Each collection we have a list of collections/bookmarks
  # get 'collections',                                to: 'collections#index',          as: :collections
  get 'collections/:collection_id',                 to: 'collections#show',           as: :collection
  get 'collections/:collection_id/new_bookmark',    to: 'collections#new_bookmark',   as: :new_bookmark
  post 'collections/:collection_id/save_bookmark',  to: 'collections#save_bookmark',  as: :save_bookmark
  delete 'collections/:collection_id/remove_bookmark/:bookmark_id',  to: 'collections#remove_bookmark',  as: :remove_bookmark

  get 'collections/:collection_id/new',             to: 'collections#new',            as: :new_collection
  get 'collections/:collection_id/edit',            to: 'collections#edit',           as: :edit_collection
  post 'collections/:collection_id/save',           to: 'collections#save',           as: :save_collection
  patch 'collections/:collection_id/update',        to: 'collections#update',         as: :update_collection
  delete 'collections/:collection_id/destroy',      to: 'collections#destroy',        as: :delete_collection

  get 'collections/:collection_id/share',             to: 'collections#share',            as: :share_collection
  post 'collections/:collection_id/save_share',       to: 'collections#save_share',            as: :save_share_collection


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :parent, polymorphic: true
  has_many :collections, as: :parent, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many :sharings, as: :shareable, dependent: :destroy
  has_many :members, through: :sharings, source: :receiver, :source_type => 'User', dependent: :destroy

  acts_as_taggable
  acts_as_taggable_on :meta

  def is_root?
    parent.instance_of? User if parent
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, except: :index

  before_action :authenticate_user!
  ## if you want spesific action for require authentication
  ## before_filter :authenticate_user!, :only => [:action1, :action2]

  # GET /collections
  # GET /collections.json
  def index
    @collection = current_user.collection
    @collections = @collection.collections
    @bookmarks = @collection.bookmarks
    @shared_collections = current_user.sharings
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collections = @collection.collections
    @bookmarks = @collection.bookmarks
    @sharings = @collection.sharings
  end

  # GET /collections/:parent/new
  def new
    @item = Collection.new
  end

  # POST /collections
  # POST /collections.json
  def save
    @item = Collection.new(collection_params)
    @collection.collections << @item
    @collection.save

    @collections = @collection.collections

    # return_to = @collection.is_root? ? collections_path : collection_path
    #
    # respond_to do |format|
    #   if @item.save
    #     format.html { redirect_to return_to, notice: 'Collection was successfully created.' }
    #     format.json { render :show, status: :created, location: @collection }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @collection.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # GET /collections/:parent/1/edit
  def edit
  end


  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    return_to = @collection.is_root? ? collections_path : collection_path
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to return_to, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
  end


  # Bookmark Actions

  def new_bookmark
    @bookmark = Bookmark.new
  end

  def edit_bookmark
    @bookmark = Bookmark.find(params[:bookmark_id])
  end

  def save_bookmark
    bookmark = Bookmark.new(bookmark_params)
    @collection.bookmarks << bookmark
    @collection.save

    @bookmarks = @collection.bookmarks

    # return_to = @collection.is_root? ? root_path : collection_path

    # respond_to do |format|
    #   if @collection.save
    #     format.html { redirect_to return_to, notice: 'Bookmark was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @collection }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @collection.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def remove_bookmark
    @bookmark = Bookmark.find(params[:bookmark_id])
    @bookmark.destroy
  end

  ### SHARE ACTIONS ###
  def share

  end

  def save_share
    sharing = Sharing.new()
    sharing.shareable = @collection

    sharing_user = User.find_for_authentication(email: params[:receiver])
    if sharing_user.nil?
      User.invite!({email: params[:receiver]}, current_user) # current_user will be set as invited_by
      sharing_user = User.find_for_authentication(email: params[:receiver])
    end

    sharing.receiver = sharing_user
    if Sharing.exists?(shareable: @collection, receiver: sharing.receiver)
      @error = "Collection has already been shared with this user."
    else
      sharing.save
    end
    @sharings = @collection.sharings

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    def authorized_user
      @collection = current_user.collections.find_by(id: params[:collection_id])
      redirect_to collections_path, notice: "Not authorized to edit this collection" if @collection.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :description, :categories, :tag_list)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :tag_list)
    end

    def sharing_params
      params.require(:sharing).permit(:shareable, :receiver)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper

	def uri_parse string
		Addressable::URI.heuristic_parse(string).to_s
	end

end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="field">
    <%= f.label :categories %>
    <%= f.text_field :categories %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/destroy.js.erb
$('#collections-list div[data-url=<%= @collection.id %>]').parent().remove();

app/views/collections/edit.js.erb
$('body').append("<%= j render(partial: 'collections/partials/collection_update')  %>");
$('.modal').modal();

$('.modal').on('hidden.bs.modal', function(){
  $(this).remove();
})

$('#collection_tag_list').selectize({
    plugins: ['restore_on_backspace', 'remove_button'],
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

app/views/collections/edit_bookmark.html.erb
<h1>Edit <%= @bookmark.title %></h1>

<%= render 'bookmark_form' %>

<% if @collection.is_root? %>
  <%= link_to 'Back', root_path %>
<% else %>
  <%= link_to 'Back', collection_path(@collection) %>
<% end %>

app/views/collections/index.html.erb
<% content_for :page_class, 'bg-light' %>
<p id="notice"><%= notice %></p>

<div class="p-x-2 p-y-2 text-xs-right">
  <%= link_to 'Add Bookmark', new_bookmark_path(@collection), class: "btn btn-primary", remote: true %>
  <%= link_to 'Add Collection', new_collection_path(@collection), class: "btn btn-primary", remote: true %>
</div>

<div class="p-x-2 p-y-2" id="collections-list">
  <%= render 'collections/partials/collections_list' if @collections.present? %>
</div>

<div class="p-x-2 p-y-2" id="collections-list">
  <%= render 'collections/partials/shared_collections_list' if @shared_collections.present? %>
</div>

<div class="p-x-2 p-y-2" id="bookmarks-list">
  <%= render 'collections/partials/bookmarks_list' if @bookmarks.present? %>
</div>

app/views/collections/new.js.erb
$('body').append("<%= j render(partial: 'collections/partials/collection_form')  %>");
$('.modal').modal();

$('.modal').on('hidden.bs.modal', function(){
  $(this).remove();
})

$('#collection_tag_list').selectize({
    plugins: ['restore_on_backspace', 'remove_button'],
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

app/views/collections/new_bookmark.js.erb
$('body').append("<%= j render(partial: 'collections/partials/bookmark_form')  %>");
$('.modal').modal();

$('.modal').on('hidden.bs.modal', function(){
  $(this).remove();
})

$('#bookmark_tag_list').selectize({
    plugins: ['restore_on_backspace', 'remove_button'],
    delimiter: ',',
    persist: false,
    create: function(input) {
        return {
            value: input,
            text: input
        }
    }
});

app/views/collections/remove_bookmark.js.erb
$('#bookmark-list tr[data-bookmark=<%= @bookmark.id %>]').remove();

app/views/collections/save.js.erb
$('.modal').modal('hide');
$('#collections-list').html("<%= j render(partial: 'collections/partials/collections_list')  %>")

app/views/collections/save_bookmark.js.erb
$('.modal').modal('hide');
$('#bookmarks-list').html("<%= j render(partial: 'collections/partials/bookmarks_list')  %>")

app/views/collections/save_share.js.erb
<% if @error.present? %>
$(".modal-body").append("<%= raw "<p>#{@error}</p>" %>")
<% else %>
$('.modal').modal('hide');
$('#collections-shares').html("<%= j render(partial: 'collections/partials/collection_shares')  %>")
<% end %>

app/views/collections/share.js.erb
$('body').append("<%= j render(partial: "collections/partials/share_collection")  %>");
$('.modal').modal();

$('.modal').on('hidden.bs.modal', function(){
  $(this).remove();
})

app/views/collections/show.html.erb
<% content_for :page_class, 'bg-grey' %>
<div class="collection-header bg-white text-dark">
  <div class="collection-info">
    <div class="p-x-2 p-y-2 text-xs-center" id="collection-info">
      <%= render 'collections/partials/collection_information' %>
    </div>
    <div id="collections-shares">
      <%= render 'collections/partials/collection_shares' %>
    </div>
    <div class="p-x-2 p-y-2 text-xs-center">
      <%= link_to 'Edit', edit_collection_path(@collection), class: 'btn btn-primary', remote: true %>
      <% if @collection.parent.is_root? %>
        <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to 'Back', collection_path(@collection.parent), class: 'btn btn-primary' %>
      <% end %>
      <%= link_to 'Add Bookmark', new_bookmark_path(@collection), class: 'btn btn-primary', remote: true %>
      <%= link_to 'Add Collection', new_collection_path, class: 'btn btn-primary', remote: true %>
      <%= link_to 'Share Collection', share_collection_path, class: 'btn btn-secondary', remote: true if @collection.parent.is_root? %>
    </div>
  </div>
</div>

<div class="container">
  <div class="p-x-2 p-y-2" id="collections-list">
    <%= render 'collections/partials/collections_list' if @collections.present? %>
  </div>

  <div class="p-x-2 p-y-2" id="bookmarks-list">
    <%= render 'collections/partials/bookmarks_list' if @bookmarks.present? %>
  </div>
</div>

app/views/collections/update.js.erb
$('.modal').modal('hide');
$('#collection-info').html("<%= j render(partial: 'collections/partials/collection_information')  %>");