config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path: '',
                      path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register',    password: 'secret', confirmation: 'verification', unlock: 'unblock' },
                      controllers: { registrations: 'registrations', invitations: 'invitations'}

  # resources :bookmarks
  # resources :collections

  # After authenticated, send user to this page
  authenticated :user do
    root 'collections#index', as: :authenticated_root
  end

  # unauthenticated :user do
  #   root 'devise/sessions#new', as: :unauthenticated_root
  # end

  # While I can't figure out how to force the user to be logged in
  root 'collections#index'


  # Inside Each collection we have a list of collections/bookmarks
  # get 'collections',                                to: 'collections#index',          as: :collections
  get 'collections/:collection_id',                 to: 'collections#show',           as: :collection
  get 'collections/:collection_id/new_bookmark',    to: 'collections#new_bookmark',   as: :new_bookmark
  post 'collections/:collection_id/save_bookmark',  to: 'collections#save_bookmark',  as: :save_bookmark
  delete 'collections/:collection_id/remove_bookmark/:bookmark_id',  to: 'collections#remove_bookmark',  as: :remove_bookmark

  get 'collections/:collection_id/new',             to: 'collections#new',            as: :new_collection
  get 'collections/:collection_id/edit',            to: 'collections#edit',           as: :edit_collection
  post 'collections/:collection_id/save',           to: 'collections#save',           as: :save_collection
  patch 'collections/:collection_id/update',        to: 'collections#update',         as: :update_collection
  delete 'collections/:collection_id/destroy',      to: 'collections#destroy',        as: :delete_collection

  get 'collections/:collection_id/share',             to: 'collections#share',            as: :share_collection
  post 'collections/:collection_id/save_share',       to: 'collections#save_share',            as: :save_share_collection


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :collection

  acts_as_taggable
  acts_as_taggable_on :meta
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!
  ## if you want spesific action for require authentication
  ## before_filter :authenticate_user!, :only => [:action1, :action2]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  def add
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :tags)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(bookmark) do |f| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<% content_for :page_class, 'bg-light' %>
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<div class="bookmarks-wrapper">
  <ul class="bookmarks-list list-inline row flex-items-xs-center">
    <% @bookmarks.each do |bookmark| %>
      <li class="col-sm-3">
        <div class="card" data-url="<%= bookmark.url %>">
          <img class="card-img-top" src="http://placeharold.com/451/270" alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title"><%= bookmark.title %></h4>
            <p class="card-text"><%= bookmark.tags %></p>
            <%= link_to 'Show', bookmark, class: 'btn btn-primary' %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>


<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.tags %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
          <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>
<% if user_signed_in? %>
  <%= link_to 'New Bookmark', new_bookmark_path %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @bookmark.tags %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>