config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  path: '',
                      path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register',    password: 'secret', confirmation: 'verification', unlock: 'unblock' },
                      controllers: { registrations: 'registrations', invitations: 'invitations'}

  # resources :bookmarks
  # resources :collections

  # After authenticated, send user to this page
  authenticated :user do
    root 'collections#index', as: :authenticated_root
  end

  # unauthenticated :user do
  #   root 'devise/sessions#new', as: :unauthenticated_root
  # end

  # While I can't figure out how to force the user to be logged in
  root 'collections#index'


  # Inside Each collection we have a list of collections/bookmarks
  # get 'collections',                                to: 'collections#index',          as: :collections
  get 'collections/:collection_id',                 to: 'collections#show',           as: :collection
  get 'collections/:collection_id/new_bookmark',    to: 'collections#new_bookmark',   as: :new_bookmark
  post 'collections/:collection_id/save_bookmark',  to: 'collections#save_bookmark',  as: :save_bookmark
  delete 'collections/:collection_id/remove_bookmark/:bookmark_id',  to: 'collections#remove_bookmark',  as: :remove_bookmark

  get 'collections/:collection_id/new',             to: 'collections#new',            as: :new_collection
  get 'collections/:collection_id/edit',            to: 'collections#edit',           as: :edit_collection
  post 'collections/:collection_id/save',           to: 'collections#save',           as: :save_collection
  patch 'collections/:collection_id/update',        to: 'collections#update',         as: :update_collection
  delete 'collections/:collection_id/destroy',      to: 'collections#destroy',        as: :delete_collection

  get 'collections/:collection_id/share',             to: 'collections#share',            as: :share_collection
  post 'collections/:collection_id/save_share',       to: 'collections#save_share',            as: :save_share_collection


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :parent, polymorphic: true
  has_many :collections, as: :parent, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_many :sharings, as: :shareable, dependent: :destroy
  has_many :members, through: :sharings, source: :receiver, :source_type => 'User', dependent: :destroy

  acts_as_taggable
  acts_as_taggable_on :meta

  def is_root?
    parent.instance_of? User if parent
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, except: :index

  before_action :authenticate_user!
  ## if you want spesific action for require authentication
  ## before_filter :authenticate_user!, :only => [:action1, :action2]

  # GET /collections
  # GET /collections.json
  def index
    @collection = current_user.collection
    @collections = @collection.collections
    @bookmarks = @collection.bookmarks
    @shared_collections = current_user.sharings
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collections = @collection.collections
    @bookmarks = @collection.bookmarks
    @sharings = @collection.sharings
  end

  # GET /collections/:parent/new
  def new
    @item = Collection.new
  end

  # POST /collections
  # POST /collections.json
  def save
    @item = Collection.new(collection_params)
    @collection.collections << @item
    @collection.save

    @collections = @collection.collections

    # return_to = @collection.is_root? ? collections_path : collection_path
    #
    # respond_to do |format|
    #   if @item.save
    #     format.html { redirect_to return_to, notice: 'Collection was successfully created.' }
    #     format.json { render :show, status: :created, location: @collection }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @collection.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # GET /collections/:parent/1/edit
  def edit
  end


  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    return_to = @collection.is_root? ? collections_path : collection_path
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to return_to, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
  end


  # Bookmark Actions

  def new_bookmark
    @bookmark = Bookmark.new
  end

  def edit_bookmark
    @bookmark = Bookmark.find(params[:bookmark_id])
  end

  def save_bookmark
    bookmark = Bookmark.new(bookmark_params)
    @collection.bookmarks << bookmark
    @collection.save

    @bookmarks = @collection.bookmarks

    # return_to = @collection.is_root? ? root_path : collection_path

    # respond_to do |format|
    #   if @collection.save
    #     format.html { redirect_to return_to, notice: 'Bookmark was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @collection }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @collection.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def remove_bookmark
    @bookmark = Bookmark.find(params[:bookmark_id])
    @bookmark.destroy
  end

  ### SHARE ACTIONS ###
  def share

  end

  def save_share
    sharing = Sharing.new()
    sharing.shareable = @collection

    sharing_user = User.find_for_authentication(email: params[:receiver])
    if sharing_user.nil?
      User.invite!({email: params[:receiver]}, current_user) # current_user will be set as invited_by
      sharing_user = User.find_for_authentication(email: params[:receiver])
    end

    sharing.receiver = sharing_user
    if Sharing.exists?(shareable: @collection, receiver: sharing.receiver)
      @error = "Collection has already been shared with this user."
    else
      sharing.save
    end
    @sharings = @collection.sharings

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:collection_id])
    end

    def authorized_user
      @collection = current_user.collections.find_by(id: params[:collection_id])
      redirect_to collections_path, notice: "Not authorized to edit this collection" if @collection.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :description, :categories, :tag_list)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :tag_list)
    end

    def sharing_params
      params.require(:sharing).permit(:shareable, :receiver)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper

	def uri_parse string
		Addressable::URI.heuristic_parse(string).to_s
	end

end

app/views/collections/partials/_bookmark_form.html.erb
<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Add new Bookmark</h4>
      </div>
      <%= form_for @bookmark, url: save_bookmark_path(collection_id: @collection.id, bookmark: @bookmark), remote: true do |f| %>
        <div class="modal-body p-x-2 p-y-2">

          <fieldset class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', autofocus: true %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url, class: 'form-control' %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :tag_list %>
            <%= f.text_field :tag_list, class: 'form-control' %>
          </fieldset>

        </div>
        <div class="modal-footer">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/partials/_bookmarks_list.html.erb
<!-- LIST ALL BOOKMARKS -->
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
        <table id="bookmark-list" class="table table-striped">
          <thead>
            <tr>
              <th class="text-xs-center">#</th>
              <th colspan="4">Bookmarks</th>
            </tr>
          </thead>
          <tbody>
            <% @bookmarks.each_with_index do |bookmark, index| %>
            <tr data-bookmark="<%= bookmark.id %>">
              <td scope="row" class="text-xs-center">
                <%= index + 1 %>
              </td>
              <td>
                <%= bookmark.title %>
              </td>
              <td>
                <%= bookmark.url %>
              </td>
              <td>
                <%= raw bookmark.tag_list %>
              </td>
              <td class="text-xs-center">
                <%= link_to 'Open', uri_parse(bookmark.url), class: 'btn btn-primary', target: '_blank' %>
                <%= link_to raw(fa_icon "trash-o"), remove_bookmark_path(collection_id: @collection.id,bookmark_id: bookmark.id), class: 'btn btn-secondary', remote: true, method: :delete %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/collections/partials/_collection_form.html.erb
<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Add new Collection</h4>
      </div>
      <%= form_for @item, url: save_collection_path(parent_id: @collection.id, collection: @item), remote: true do |f| %>
        <div class="modal-body p-x-2 p-y-2">

          <fieldset class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', autofocus: true %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :tag_list %>
            <%= f.text_field :tag_list, class: 'form-control' %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :categories %>
            <%= f.text_field :categories, class: 'form-control' %>
          </fieldset>

        </div>
        <div class="modal-footer">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/partials/_collection_information.html.erb
<h2><%= @collection.name %></h2>
<p><%= @collection.description %></p>
<p><%= raw @collection.tag_list %><br><%= @collection.categories %></p>
<br>
<p id="notice"><%= notice %></p>

app/views/collections/partials/_collection_shares.html.erb
<% if @sharings.present? %>
	<div class="p-x-2 p-y-2 text-xs-center">
		<h4>Shared with</h4>
		<span class="user-image">
			<% user_info = current_user.name || current_user.email %>
			<%= image_tag @collection.parent.parent.avatar.thumb.url, size: '50x50', alt: user_info, title: user_info, class: "img-responsive img-circle" %>
		<% @sharings.each do |share| %>
			<span class="user-image">
				<% user_info = share.receiver.name || share.receiver.email %>
				<%= image_tag share.receiver.avatar.thumb.url, size: '50x50', alt: user_info, title: user_info, class: "img-responsive img-circle #{"opacity-50" if !share.receiver.is_active?}" %>
			</span>
		<% end %>
	</div>
<% end %>

app/views/collections/partials/_collection_update.html.erb
<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Add new Collection</h4>
      </div>
			<%= form_for @collection, url: update_collection_path(collection_id: @collection.id), remote: true do |f| %>
        <div class="modal-body p-x-2 p-y-2">

          <fieldset class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', autofocus: true %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :description %>
            <%= f.text_field :description, class: 'form-control' %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :tag_list %>
            <%= f.text_field :tag_list, value: @collection.tag_list.to_s, class: 'form-control' %>
          </fieldset>

          <fieldset class="form-group">
            <%= f.label :categories %>
            <%= f.text_field :categories, class: 'form-control' %>
          </fieldset>

        </div>
        <div class="modal-footer">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/partials/_collections_list.html.erb
<h1>Collections</h1>

<div class="bookmarks-wrapper">
  <ul class="bookmarks-list list-inline row">
    <% @collections.each do |collection| %>
      <li class="col-sm-3">
        <div class="card" data-url="<%= collection.id %>">
          <div class="card-block">
            <h4 class="card-title"><%= collection.name %></h4>
            <p class="card-text"><%= raw collection.tag_list %></p>
            <p class="card-text"><%= collection.categories %></p>
            <%= link_to 'Show', collection, class: 'btn btn-primary' %>
            <%= link_to raw(fa_icon "trash-o"), delete_collection_path(collection_id: collection.id), class: 'btn btn-primary', remote: true, method: :delete %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/collections/partials/_share_collection.html.erb
<div class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Share <%= @collection.name %></h4>
      </div>
      <%= form_tag save_share_collection_path, remote: true do %>
        <div class="modal-body">
          <fieldset class="form-group">
            <%= label_tag :receiver, "friend's email" %>
            <%= email_field_tag :receiver, nil, class: 'form-control', placeholder: 'Enter email', autofocus: true  %>
          </fieldset>
        </div>
        <div class="modal-footer">
          <%= submit_tag "Invite", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/collections/partials/_shared_collections_list.html.erb
<h1>Shared Collections</h1>

<div class="bookmarks-wrapper">
  <ul class="bookmarks-list list-inline row">
    <% @shared_collections.each do |shared| %>
			<% collection = shared.shareable %>
      <li class="col-sm-3">
        <div class="card" data-url="<%= collection.id %>">
          <div class="card-block">
            <h4 class="card-title"><%= collection.name %></h4>
            <p class="card-text"><%= raw collection.tag_list %></p>
            <p class="card-text"><%= collection.categories %></p>
            <%= render 'collections/partials/small_share_list', collection: collection if collection.sharings.present? %>
            <%= link_to 'Show', collection, class: 'btn btn-primary' %>
            <%= link_to raw(fa_icon "trash-o"), delete_collection_path(collection_id: collection.id), class: 'btn btn-primary', remote: true, method: :delete %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/collections/partials/_small_share_list.html.erb
<div class="collection-users">
  Shared with:
  <br>
  <span class="user-image">
    <% user_info = current_user.name || current_user.email %>
    <%= image_tag collection.parent.parent.avatar.thumb.url, size: '25x25', alt: user_info, title: user_info, class: "img-responsive img-circle" %>
  </span>
  <% collection.sharings.each do |share| %>
    <span class="user-image">
      <% user_info = share.receiver.name || share.receiver.email %>
      <%= image_tag share.receiver.avatar.thumb.url, size: '25x25', alt: user_info, title: user_info, class: "img-responsive img-circle #{"opacity-50" if !share.receiver.is_active?}" %>
    </span>
  <% end %>
</div>